# Generated by Django 5.2.14 on 2026-05-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
    ]
